title: 大叔說財經科技投資
description: 每日財經科技投資資訊，聊美股、加密貨幣、AI與投資
author: 大叔
email: timhun@ms28.hinet.net
language: zh-tw
category: Business
subcategory: Investing
image: https://timhun.github.io/daily-podcast-stk/img/cover.jpg
explicit: no
