name: Daily Strategy Report

on:
  schedule:
    # 每天台灣時間 06:10 -> UTC = 前一天 22:10
    - cron: '10 22 * * *'
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests pytz

      - name: Run report generator
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
        run: |
          mkdir -p scripts
          # 假設你會把 generate_daily_report.py 放到 scripts/ 下
          python scripts/generate_daily_report.py

      - name: Commit and push report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_report.md || true
          git commit -m "每日策略報告 $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "Push failed"
