name: Data-Fetch

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣時間 06:00 (UTC 22:00 前一天)
    - cron: '0 6 * * *'   # 台灣時間 14:00 (UTC 06:00)
    - cron: '0 11 * * *'  # 台灣時間 19:00 (UTC 11:00)
  workflow_dispatch:
    inputs:
      mode:
        description: '運行模式 (hourly/daily/auto/manual)'
        required: true
        default: 'auto'
        type: choice
        options:
          - hourly
          - daily
          - auto
          - manual
      podcast_mode:
        description: '數據模式 (tw/us/both)'
        required: true
        default: 'both'
        type: choice
        options:
          - tw
          - us
          - both

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance

      - name: Set environment variables
        run: |
          echo "MODE=${{ github.event.inputs.mode || 'daily' }}" >> $GITHUB_ENV
          echo "MANUAL_TRIGGER=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'manual' && '1' || '0' }}" >> $GITHUB_ENV
          HOUR_TW=$(TZ=Asia/Taipei date +%H)
          if [ "$HOUR_TW" = "06" ] || [ "${{ github.event.inputs.podcast_mode }}" = "us" ] || [ "${{ github.event.inputs.podcast_mode }}" = "both" ]; then
            echo "FETCH_US=1" >> $GITHUB_ENV
          fi
          if [ "$HOUR_TW" = "14" ] || [ "$HOUR_TW" = "19" ] || [ "${{ github.event.inputs.podcast_mode }}" = "tw" ] || [ "${{ github.event.inputs.podcast_mode }}" = "both" ]; then
            echo "FETCH_TW=1" >> $GITHUB_ENV
          fi
        env:
          GITHUB_ENV: ${{ github.env }}

      - name: Fetch market data (US - QQQ)
        if: env.FETCH_US == '1'
        run: |
          export PODCAST_MODE=us
          python scripts/fetch_market_data.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Fetch market data (TW - 0050.TW)
        if: env.FETCH_TW == '1'
        run: |
          export PODCAST_MODE=tw
          python scripts/fetch_market_data.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Check data files
        run: |
          ls -l data/
          for file in data/daily_0050.TW.csv data/hourly_0050.TW.csv data/daily_QQQ.csv data/hourly_QQQ.csv; do
            if [ -f "$file" ]; then
              echo "$file exists, last modified: $(stat -c %y "$file")"
            else
              echo "Warning: $file does not exist"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/*.csv
          git commit -m "Update market data files [skip ci]" || echo "No changes to commit"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data-reports-${{ github.run_id }}
          path: |
            data/*.csv
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
