name: Daily Podcast Generation

on:
  schedule:
    - cron: '0 22 * * *' # 每天台灣時間早上 6:00 (UTC 前日 22:00)

jobs:
  generate_podcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y ffmpeg # 安裝 FFmpeg

      - name: Set up Git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Generate podcast
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}    # 在 GitHub Secrets 中設定
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}  # 在 GitHub Secrets 中設定
        run: python scripts/main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          commit_message: "自動更新 Podcast"
