name: Daily Podcast Generation and Deployment

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣時間 06:00 (UTC 前日 22:00)
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run podcast generation
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: python scripts/main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add audio/ transcripts/ feed.xml data/script.txt
          git commit -m "Add podcast episode and transcript for $(date +%Y%m%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
