name: Auto-Trading-Loop

on:
  schedule:
    - cron: '0 * * * 1-5'  # 工作日每小時 UTC 00:00 (台灣 08:00) 至 23:00 (次日 07:00)
  workflow_dispatch:
    inputs:
      mode:
        description: '運行模式 (hourly/daily/weekly/auto/manual)'
        required: true
        default: 'auto'
        type: choice
        options:
          - hourly
          - daily
          - weekly
          - auto
          - manual

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance backtrader requests pytz

      - name: Run pipeline
        run: python scripts/run_pipeline.py
        env:
          MODE: ${{ github.event.inputs.mode || 'auto' }}
          MANUAL_TRIGGER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'manual' && '1' || '0' }}
          USE_LLM: 1
          SYMBOL: 0050.TW
          REPORT_DIR: data
          DATA_DIR: data
          HISTORY_FILE: data/strategy_history.json
          TARGET_RETURN: 0.02
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL: llama-3.1-70b-versatile
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: Tim.oneway@gmail.com

      - name: Check CSV files
        run: |
          ls -l data/
          for file in data/*.csv; do
            if [ -f "$file" ]; then
              echo "$file exists, last modified: $(stat -c %y "$file")"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # 動態添加現有檔案，忽略不存在的路徑
          git add data/*.json data/*.csv
          # 檢查並添加 podcast 檔案
          if [ -f "docs/podcast/$(date +%Y%m%d)_tw/script.txt" ]; then
            git add docs/podcast/$(date +%Y%m%d)_tw/script.txt
          fi
          git commit -m "Update generated files [skip ci]" || echo "No changes to commit"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.run_id }}
          path: |
            data/*.json
            data/*.csv
            docs/podcast/*/*_tw/script.txt
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false