name: Generate TW Market Podcast Script

on:
  schedule:
    # 每天下午2點（UTC+8 = UTC 06:00）
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generate-tw-podcast:
    runs-on: ubuntu-latest

    env:
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and update TW market data
        run: |
          python datarecord.py --tickers "^TWII,0050.TW,2330.TW"

      - name: Generate TW podcast script
        run: |
          python generate_script.py --tw

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/ docs/podcast/
          git commit -m "Update TW market data and podcast script for $(date +%Y%m%d)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}