name: Daily Podcast Generation and Deployment

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣時間 06:00 (UTC 前日 22:00)
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > credentials.json

      - name: Fetch data and news
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: |
          python scripts/fetch_data.py
          curl -o data/news.json "YOUR_GOOGLE_APPS_SCRIPT_URL"  # 替換為 Web App URL

      - name: Generate script with Grok API
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: |
          python scripts/generate_script.py

      - name: Convert text to audio
        run: python scripts/text_to_audio.py

      - name: Generate RSS feed
        run: python scripts/generate_rss.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add audio/ feed.xml data/script.txt data/news.json
          git commit -m "Add podcast episode for $(date +%Y%m%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
