# .github/workflows/taiex-scraper.yml
name: TAIEX Daily Scraper

on:
  schedule:
    # 每週一到週五 台灣時間 15:30 (UTC+8)
    # UTC時間為 07:30，考慮時區差異
    - cron: '30 7 * * 1-5'
  
  # 允許手動觸發
  workflow_dispatch:

jobs:
  scrape-taiex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas pytz
    
    - name: Set timezone to Asia/Taipei
      run: |
        sudo timedatectl set-timezone Asia/Taipei
        echo "Current time: $(date)"
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run TAIEX scraper
      run: python scripts/taiex_scraper.py
      env:
        TZ: Asia/Taipei
    
    - name: Check if data was updated
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Auto update TAIEX data - $(date '+%Y-%m-%d %H:%M:%S')"
        git push
    
    - name: Create release (weekly)
      if: steps.check_changes.outputs.changes == 'true' && github.event.schedule == '30 7 * * 5'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: weekly-${{ github.run_number }}
        release_name: Weekly TAIEX Data ${{ github.run_number }}
        body: |
          自動生成的週度台灣加權指數資料
          時間: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false