name: Update Data

on:
  schedule:
    - cron: '0 6 * * *'  # 每天UTC時間6點執行，即UTC+8時間下午2點
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas vectorbt twstock yfinance pytz numba==0.58.1
        continue-on-error: false

      - name: Update data
        run: python scripts/tw_datarecord.py
        continue-on-error: false

      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "tim.oneway@gmail.com"
          git config --global user.name "BBM"
          git add -A
          git commit -m "Automated data update $(date +'%Y-%m-%d')" -a || echo "No changes to commit"
          git push origin main