name: US Podcast Pipeline
on:
  schedule:
    - cron: '35 21 * * *'  # UTC 21:30 = 台灣 05:30 次日
  workflow_dispatch:

jobs:
  produce:
    runs-on: ubuntu-latest
    env:
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        EMAIL: ${{ secrets.EMAIL }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        COQUI_TOS_AGREED: 1 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      # 2. Install all Python dependencies. This will now handle TTS from GitHub.
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - run: python main.py --mode us
        
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f rss/ data/ logs/ docs/ strategies/
          git diff --staged --quiet || git commit -m "US Podcast ${{ github.event.schedule || 'manual' }} published"
          git push
