name: Weekly Learning (0050)

on:
  schedule:
    - cron: '0 18 * * 6'   # Sat 18:00 UTC -> Sun 02:00 Taipei (weekly)
  workflow_dispatch:

permissions:
  contents: write  # for committing back results

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run weekly pipeline
        run: python run_pipeline.py
      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-reports
          path: reports/
      - name: Commit reports back to repo
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports/*.json || true
          git commit -m "Auto update reports: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "no changes to commit"
          git push origin HEAD:${{ github.ref_name }}